apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat
  namespace: prod
spec:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: tomcat
