apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: naren
  namespace: production
spec:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: naren
