apiVersion: v1
kind: Service
metadata:
  labels:
    service: naren
  name: naren
  namespace: production
spec:
  type: NodePort
  ports:
  - name: tomcat
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30014
  selector:
    service: naren
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: naren
  namespace: production
