kind: Service
apiVersion: v1
metadata:
  labels:
    service: apidocs
  name: tomcat7-lb
  namespace: production
spec:
  selector:
    app: tomcat7
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30014
  type: LoadBalancer
